JustDoIt/ViewModels/UserViewModel.cs
namespace JustDoIt.ViewModels
{
    public class UserViewModel
    {
        public string Name { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Authorized { get; set; }
    }
}

JustDoIt/Controllers/BaseController.cs
using System.Web.Mvc;
using JustDoIt.Auth;
using JustDoIt.DB.Entity;
using JustDoIt.Windsor;

namespace JustDoIt.Controllers
{
    public abstract class BaseController : Controller
    {
        protected readonly IAuthentication Authentication = IocContainer.Resolve<IAuthentication>();

        public User CurrentUser
        {
            get
            {
                return ((IUserProvider)HttpContext.User.Identity).User;
            }
        }
    }
}

JustDoIt/Controllers/HomeController.cs
using System.Web.Mvc;
using JustDoIt.ViewModels;

namespace JustDoIt.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index(UserViewModel model)
        {
            return View(model);
        }

        public ActionResult LogOut()
        {
            Authentication.LogOut();

            return RedirectToAction("Index", "Login");
        }

    }
}

JustDoIt/Controllers/IndexController.cs
using System.Web.Mvc;
using JustDoIt.Mappers;

namespace JustDoIt.Controllers
{
    public class IndexController : BaseController
    {
        public ActionResult Index()
        {
            return CurrentUser != null ? View(UserMapper.Map(CurrentUser)) : View();
        }
    }
}

JustDoIt/Controllers/LoginController.cs
using System.Web.Mvc;
using JustDoIt.SERVICE;
using JustDoIt.ViewModels;

namespace JustDoIt.Controllers
{
    public class LoginController : BaseController
    {
        private readonly IUserService _userService;

        public LoginController(IUserService userService)
        {
            _userService = userService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = _userService.GetUser(userViewModel.Name, userViewModel.Password);

                if (user != null)
                {
                    Authentication.LogIn(user);
                    return RedirectToAction("Index", "Index");
                }

                ModelState["Password"].Errors.Add("Данные введены неверно");
            }
            return View(userViewModel);
        }
    }
}

JustDoIt/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication2.Controllers
{
    public class RegisterController : Controller
    {
        //
        // GET: /Register/

        public ActionResult Index()
        {
            return View();
        }

    }
}

JustDoIt/Controllers/RegistrationController.cs
using System.Web.Mvc;
using JustDoIt.Mappers;
using JustDoIt.SERVICE;
using JustDoIt.ViewModels;

namespace JustDoIt.Controllers
{
    public class RegistrationController : BaseController
    {
        private readonly IUserService _userService;

        public RegistrationController(IUserService userService)
        {
            _userService = userService;
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserViewModel userViewModel)
        {
            var user = UserMapper.Map(userViewModel);
            var result = _userService.CreateUser(user);

            switch (result)
            {
                case CreateUserResult.NickNameUsed:
                    return View(userViewModel);
                case CreateUserResult.Success:
                    Authentication.LogIn(user);
                    break;
            }

            return RedirectToAction("Index", "Index");
        }

    }
}

JustDoIt/Controllers/WelcomeController.cs
using System.Web.Mvc;

namespace JustDoIt.Controllers
{
    public class WelcomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

JustDoIt/Views/Home/Index.cshtml
@model JustDoIt.ViewModels.UserViewModel

@{
    ViewBag.Title = "Home";
    ViewBag.Model = Model;
    Layout = "~/Views/Shared/ContentsLayout.cshtml";
}

JustDoIt/Views/Index/Index.cshtml
@model JustDoIt.ViewModels.UserViewModel

@(Model != null ? Html.Action("Index", "Home", Model) : Html.Action("Index", "Welcome"))

JustDoIt/Views/Login/Index.cshtml
@model JustDoIt.ViewModels.UserViewModel

@{
    ViewBag.Title = "Authorization";
    ViewBag.Model = Model;
    Layout = "~/Views/Shared/ContentsLayout.cshtml";
}

<div class="container">
    @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "form-horizontal form-box" }))
    {
        <fieldset>
            <legend>Авторизация</legend>
            <div class="form-group">
                <label class="col-sm-4 control-label" for="Name">
                    Name
                </label>
                <div class="col-sm-8">
                    @Html.TextBox("Name", "", new {@class = "form-control input-xlarge"})
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label" for="Password">
                    Password
                </label>
                <div class="col-sm-8">
                    @Html.Password("Password", "", new {@class = "form-control input-xlarge"})
                </div>
            </div>
            <div class="form-group">
                <p class="col-sm-8 col-sm-offset-4 text-danger">@Html.ValidationMessage("Password")</p>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary col-sm-offset-4">
                    Войти
                </button>
            </div>
        </fieldset>
    }
</div>

JustDoIt/Views/Register/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

JustDoIt/Views/Shared/ContentsLayout.cshtml
@using System.Web.UI.WebControls
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title> 
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-default">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Just Do It</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    @if (ViewBag.Model == null || !ViewBag.Model.Authorized)
                    {
                        <li><a href="#">Features</a></li>
                        <li><a href="/Login">Log in</a></li>
                        <li><a class="menu-signup-button" href="/Registration/Register">Registration</a></li>
                    }
                    else
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@(ViewBag.Model.Name) <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/Profile">View profile</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/Home/LogOut">Log out</a></li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
    </nav>

@RenderBody()
@RenderSection("scripts", required: false)
</body>
</html>

JustDoIt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title> 
    @Scripts.Render("~/bundles/jquery")
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    @Styles.Render("~/Content/WelcomeStyles.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
@RenderBody()
@RenderSection("scripts", required: false)
</body>
</html>

JustDoIt/Views/Test/Index.cshtml
@using System.Web.Mvc.Html

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<center>
    <h1>Записи из базы данных</h1>
</center>
<table class="centered">
    <thead>
        <tr>
            <th>Ник</th>
            <th>Пароль</th>
            <th>Имя</th>
            <th>Фамилия</th>
        </tr>
    </thead>
</table>

JustDoIt/Views/Welcome/Index.cshtml
@{
    ViewBag.Title = "Welcome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="container">
    <nav class="navbar">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Just Do It</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Features</a></li>
                    <li><a href="/Login">Log in</a></li>
                    <li><a class="menu-signup-button" href="/Registration/Register">Get started</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<main class="welcome-content">
    <section class="welcome-banner">
        <h1 class="welcome-heading">
            Управляйте своими проектами
        </h1>
        <p class="welcome-tagline">
            хо-хо-хо
        </p>
        <p>
            <a class="welcome-signup-button" href="/account/signup/">
                Начать!
            </a>
        </p>
    </section>
    <section class="welcome-description">
        какое-то описание
    </section>
</main>